### ISSUE TITLE
canXXXToCanal functions return always false

### ISSUE THREAD

**Issue by BlueAndi** [grodansparadis/vscp_software#101]
Hi Ake,

in all canXXXToCanal functions the rv variable is never set to true and the function returns always false.

Best regards
Andreas

**Comment by grodansparadis** [comment]
Where are they?

**Comment by BlueAndi** [comment]
level1\rs485\common\rs485obj.cpp
level1\rs485\win32\test\rs485drv.cpp
level1\can232\win32\Test\CAN232Drv.cpp
level1\can232\common\can232obj.cpp
level1\can232\linux\can232obj.cpp

**Comment by grodansparadis** [comment]
OK will stack this up  as for now. Busy with other things at the moment.

/Ake

Andreas Merkle skrev den 2015-03-12 22:51:
>
> level1\rs485\common\rs485obj.cpp
> level1\rs485\win32\test\rs485drv.cpp
> level1\can232\win32\Test\CAN232Drv.cpp
> level1\can232\common\can232obj.cpp
> level1\can232\linux\can232obj.cpp
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/grodansparadis/vscp_software/issues/101#issuecomment-78640003>.
>

-- 
Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN
Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
http://www.grodansparadis.com http://www.vscp.org



---
Detta e-postmeddelande har sökts igenom efter virus med antivirusprogram från Avast.
http://www.avast.com
