### ISSUE TITLE
Not possible to allow everyone to access the daemon remotely

### ISSUE THREAD

**Issue by mamac** [grodansparadis/vscp_software#122]
Hello

I have the setup below in vscpd.conf:

    <remoteuser>
        <user>
            <name>admin</name>
            <password>d50c3180375c27927c22e42a379c3f67</password>
            <privilege>admin</privilege>
            <allowfrom>*</allowfrom>
        </user>
        <user>
            <name>user</name>
            <password>ee11cbb19052e40b07aac0ca060c23ee</password>
            <privilege>admin</privilege>
            <allowfrom>*</allowfrom>
        </user>
    </remoteuser>
But the client has an access denied message while connecting to the daemon via websocket.

Thank you,
JM

**Comment by grodansparadis** [comment]
Hmmm... Strange looks like it works here. I will have a check again.

/Ake

mamac skrev den 2015-04-17 19:09:
>
> Hello
>
> I have the setup below in vscpd.conf:
>
> |<remoteuser>
>      <user>
>          <name>admin</name>
>          <password>d50c3180375c27927c22e42a379c3f67</password>
>          <privilege>admin</privilege>
>          <allowfrom>*</allowfrom>
>      </user>
>      <user>
>          <name>user</name>
>          <password>ee11cbb19052e40b07aac0ca060c23ee</password>
>          <privilege>admin</privilege>
>          <allowfrom>*</allowfrom>
>      </user>
> </remoteuser>
> |
>
> But the client has an access denied message while connecting to the 
> daemon via websocket.
>
> Thank you,
> JM
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/grodansparadis/vscp_software/issues/122>.
>

-- 
Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN
Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
http://www.grodansparadis.com http://www.vscp.org



---
Detta e-postmeddelande har sökts igenom efter virus med antivirusprogram från Avast.
http://www.avast.com

**Comment by grodansparadis** [comment]
This should be fixed now.  Works on demo.vscp.org  Open again if not
