### ISSUE TITLE
vscpworks.exe is not a valid Win32 application (vscp-1.0.1.2-x86.exe)

### ISSUE THREAD

**Issue by waaslandwolf** [grodansparadis/vscp_software#131]
After installing vscp-1.0.1.2-x86.exe, when running vscpworks.exe, I get an error "c:\Program Files\VSCP\vscpworks.exe is not a valid Win32 application."

Did a proper uninstall of the previous version + deleted the "c:\Program Files\VSCP" manually before installing the new version.

Installed MS Visual C++ 2013 Redistributable (x86) 12.0.30501 during installation.

**Comment by grodansparadis** [comment]
OS?

Works OK here. Could maybe be a mismatch of 32/64 bit dll's. I will 
check that. But don't have time tight now.

waaslandwolf skrev den 2015-05-04 20:14:
>
> After installing vscp-1.0.1.2-x86.exe, when running vscpworks.exe, I 
> get an error "c:\Program Files\VSCP\vscpworks.exe is not a valid Win32 
> application."
>
> Did a proper uninstall of the previous version + deleted the 
> "c:\Program Files\VSCP" manually before installing the new version.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/grodansparadis/vscp_software/issues/131>.
>

-- 
Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN
Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
http://www.grodansparadis.com http://www.vscp.org



---
Detta e-postmeddelande har sökts igenom efter virus med antivirusprogram från Avast.
http://www.avast.com

**Comment by waaslandwolf** [comment]
OS is Windows XP SP3 with latest updates.

I assume Win development isn't high on your priority list. I don't 
really need the new win version, if I can get 1.0.0.43 to connect to the 
daemon then that's fine as well.

David.

On 4/05/2015 20:34, Åke Hedman wrote:
> OS?
>
> Works OK here. Could maybe be a mismatch of 32/64 bit dll's. I will
> check that. But don't have time tight now.
>
> waaslandwolf skrev den 2015-05-04 20:14:
> >
> > After installing vscp-1.0.1.2-x86.exe, when running vscpworks.exe, I
> > get an error "c:\Program Files\VSCP\vscpworks.exe is not a valid Win32
> > application."
> >
> > Did a proper uninstall of the previous version + deleted the
> > "c:\Program Files\VSCP" manually before installing the new version.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/grodansparadis/vscp_software/issues/131>.
> >
>
> -- 
> Be Hungry - Stay Foolish!
> Åke Hedman, Grodans Paradis AB / Paradise of the Frog
> Brattbergavägen 17, 82050 LOS, SWEDEN
> Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
> http://www.grodansparadis.com http://www.vscp.org
>
>
>
> ---
> Detta e-postmeddelande har sökts igenom efter virus med 
> antivirusprogram från Avast.
> http://www.avast.com
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/grodansparadis/vscp_software/issues/131#issuecomment-98806710>.
>



---
This email has been checked for viruses by Avast antivirus software.
http://www.avast.com

**Comment by grodansparadis** [comment]
waaslandwolf skrev den 2015-05-04 20:36:
> OS is Windows XP SP3 with latest updates.
OK   XP is not supported any longer but if you could run 1.0.0 then it 
probably should work.

>
> I assume Win development isn't high on your priority list. I don't
> really need the new win version, if I can get 1.0.0.43 to connect to the
> daemon then that's fine as well.
1.0.0 will never do that.

/Ake

-- 
Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN
Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
http://www.grodansparadis.com http://www.vscp.org


---
Detta e-postmeddelande har sökts igenom efter virus med antivirusprogram från Avast.
http://www.avast.com
