### ISSUE TITLE
"Failed to update data" when writing register

### ISSUE THREAD

**Issue by waaslandwolf** [grodansparadis/vscp_software#136]
Context:
- VSCP 1.0.1.12 on Ubuntu 14.04 LTS
- VSCP daemon running locally, VSCPworks running locally
- USB2CAN converter to a bus with 21 Mespelare v9 modules

History:
- ip link set can0 up
- /etc/init.d/vscpd start
- /usr/local/bin/vscpworks & 
- Start VSCP client window, connect to daemon
- Start VSCP device configuration window, connect to daemon

Known good baseline:
- read registers for device 0x0D, read successful
- change value for register 0x27, click Update, write successful, functionality as expected (shows register write worked)

Bug:
- wait half an hour or so
- change value for register 0x27, click Update. Lots of debug messages in the terminal window where VSCPworks was started, "Failed to update data" message window. 
- kill -9 [vscpd and vscpworks], daemon restart, vscpworks restart, register now reads and writes correctly.
- When testing functionality or re-reading the node's registers, it is clear that the data was written to the node correctly, but VSCPworks still threw an error.
- Changing the node ID input box on the top of the screen and updating (re-reading) all the node's registers also makes the error go away.

**Comment by grodansparadis** [comment]
Ok will check

waaslandwolf skrev den 2015-05-08 21:13:
>
> Context:
>
>   * VSCP 1.0.1.12 on Ubuntu 14.04 LTS
>   * VSCP daemon running locally, VSCPworks running locally
>   * USB2CAN converter to a bus with 21 Mespelare v9 modules
>
> History:
>
>   * ip link set can0 up
>   * /etc/init.d/vscpd start
>   * /usr/local/bin/vscpworks &
>   * Start VSCP client window, connect to daemon
>   * Start VSCP device configuration window, connect to daemon
>
> Known good baseline:
>
>   * read registers for device 0x0D, read successful
>   * change value for register 0x27, click Update, write successful,
>     functionality as expected (shows register write worked)
>
> Bug:
>
>   * wait half an hour or so
>   * change value for register 0x27, click Update. Lots of debug
>     messages in the terminal window where VSCPworks was started,
>     "Failed to update data" message window.
>   * kill -9 [vscpd and vscpworks], daemon restart, vscpworks restart,
>     register now reads and writes correctly.
>   * When testing functionality or re-reading the node's registers, it
>     is clear that the data was written to the node correctly, but
>     VSCPworks still threw an error.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/grodansparadis/vscp_software/issues/136>.
>

-- 
Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN
Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
http://www.grodansparadis.com http://www.vscp.org



---
Detta e-postmeddelande har sökts igenom efter virus med antivirusprogram från Avast.
http://www.avast.com

**Comment by grodansparadis** [comment]
I have not forgotten about this one. Just haven't found it. Sorry for the delay.  Bit I can acknowledge the behavior.
