### ISSUE TITLE
Issue with Scan function?

### ISSUE THREAD

**Issue by waaslandwolf** [grodansparadis/vscp_software#146]
VSCPworks 1.0.1.21 Neon on Ubuntu LTS14.0

- daemon already running for several days/weeks
- open _VSCP Client window_, select interface "_TCPIP: localhost_"
- client window opens, can see events on the bus

- Open "_Scan for device..._" window
- Select interface "_TCP/IP: localhost_"
- Scan window opens
- Click "_Scan_" button, _scan from_ 1 _scan to_ 255 was already filled in
- Scan window opens window "_Scanning for VSCP devices, reading registers_"
- VSCPworks main window throws error window "_No interface specified. Please select one OK_" Clicking _OK_ closes 2 above windows and returns to scan window. No devices found.

**Comment by grodansparadis** [comment]
Yes you must select an interface for this to work. Yes I know the naming is confusing, But on the daemon the interfaces is each driver, client etc connected. This is because a nickname have no meaning at this level. Only GUID's have. And it would take a lifetime to scan for the.m

**Comment by waaslandwolf** [comment]
Correct - because TCP/IP: localhost I assumed that it would have an interface assigned, which wasn't the case. Clicked Edit and selected level2socketcan driver, now all is well.

**Comment by grodansparadis** [comment]
Great.

waaslandwolf skrev den 2015-06-02 13:43:
>
> Correct - because TCP/IP: localhost I assumed that it would have an 
> interface assigned, which wasn't the case. Clicked Edit and selected 
> level2socketcan driver, now all is well.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/grodansparadis/vscp_software/issues/146#issuecomment-107925012>.
>

-- 
Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN
Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
http://www.grodansparadis.com http://www.vscp.org



---
Detta e-postmeddelande har sökts igenom efter virus med antivirusprogram från Avast.
http://www.avast.com
