### ISSUE TITLE
Daemon respond with websocket authentication AUTH0 twice

### ISSUE THREAD

**Issue by BlueAndi** [grodansparadis/vscp_software#155]
15:10:42.222 Cmd: C;CHALLENGE
15:10:42.226 Rsp: +;AUTH0;124971ae8a2df676a1379238cf0842a8
15:10:42.232 Cmd: C;AUTH;admin;e61ff4fca8f0a23a52374de21cf2f0b5
15:10:42.331 Rsp: +;AUTH0;124971ae8a2df676a1379238cf0842a8 <----------
15:10:42.631 Rsp: +;AUTH1

**Comment by grodansparadis** [comment]
OK noted. Will check.

**Comment by grodansparadis** [comment]
This is correct as "CHALLANGE" is sent. If "CHALLANGE" is not sent one should be received.

**Comment by BlueAndi** [comment]
Sry ... I am standing on the line ;-) ...
I see two commands and three responses ... don't get it why there are more responses, than commands?

**Comment by grodansparadis** [comment]
The "CHALLANGE" command is not needed. It just trigger the same response
that is sent out on a connect.

Den 2015-09-17 kl. 20:39, skrev Andreas Merkle:
> Sry ... I am standing on the line ;-) ...
> I see two commands and three responses ... don't get it why there are
> more responses, than commands?
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/grodansparadis/vscp_software/issues/155#issuecomment-141182693>.
> 

-- 
Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN
Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
http://www.grodansparadis.com http://www.vscp.org

**Comment by BlueAndi** [comment]
Ahh ... ok ... now I got it. Thanks for explanation.
