### ISSUE TITLE
Websocket WRITEVAR returns success although the value was invalid

### ISSUE THREAD

**Issue by BlueAndi** [grodansparadis/vscp_software#158]
The DEMOVARIABLE type is boolean.

22:15:36.244 Cmd: C;WRITEVAR;DEMOVARIABLE;asfsadfsadf
22:15:36.380 Rsp: +;WRITEVAR

**Comment by grodansparadis** [comment]
All of the set variable parts are relaxed in a sense that they set a default value when an "invalid value" is requested, in this case "false".  We leave this open. Need to think.  May be better to be more strict but not sure now.

**Comment by BlueAndi** [comment]
If the variable is reset to a default value, receiving the current value back with the positive reply will help. Otherwise I have to read the value always back, after a successful write.

**Comment by grodansparadis** [comment]
That is a good idea!

**Comment by BlueAndi** [comment]
Implemented.
