### ISSUE TITLE
Websocket RESETVAL returns no value back

### ISSUE THREAD

**Issue by BlueAndi** [grodansparadis/vscp_software#160]
It would be good to receive the value with the positive reply back. Otherwise after the variable is reset, you have to read it back again.

**Comment by grodansparadis** [comment]
In the rest case the default value is at least known. If a positive reply the variable have the default value. Listed here http://www.vscp.org/docs/vscpd/doku.php?id=vscp_daemon_variable_string_write_format

**Comment by BlueAndi** [comment]
Nevertheless getting the reset value back would be better. If all "known" reset values are implemented hardcoded, the sourcecode will always be false, because the specification changed (murphys law). And bad is, that I have to know the variable type, otherwise I can not imagine how the reset value is.

And its quite easy to return it back. ;-)

**Comment by grodansparadis** [comment]
On the other hand you can use writevar to obtain what you want. resetvar  "reste".
