### ISSUE TITLE
Websocket description about read table values

### ISSUE THREAD

**Issue by BlueAndi** [grodansparadis/vscp_software#163]
In the description the keyword "GT" is missing in general.

**Comment by grodansparadis** [comment]
OK

Den 2015-07-24 kl. 15:15, skrev Andreas Merkle:
>
> In the description the keyword "GT" is missing in general.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/grodansparadis/vscp_software/issues/163>.
>

-- 
Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN
Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
http://www.grodansparadis.com http://www.vscp.org



---
Detta e-postmeddelande har sökts igenom efter virus med antivirusprogram från Avast.
https://www.avast.com/antivirus

**Comment by grodansparadis** [comment]
Was under the heading TABLE.  Changed to GT
