### ISSUE TITLE
Rename JSON property "session-id" to session_id

### ISSUE THREAD

**Issue by dinguluer** [grodansparadis/vscp_software#167]
There is a bug in the naming convection for session-id JSON property.

Please change the name of JSON property "session-id" to session_id, because :--

JSON object properties naming convection it recommends that:--
1/ Property names must be camel-cased, ascii strings.
2/ The first character must be a letter, an underscore (_) or a dollar sign ($).

**Comment by BlueAndi** [comment]
Can you verify the bugfix please Dinesh?

**Comment by dinguluer** [comment]
>> Can you verify the bugfix please Dinesh?
Is this change made to the vscpd demon ?

Regards,
Dinesh

**Comment by grodansparadis** [comment]
Send this to the group also as more people are affected.

Yes it is.  Some other changes to.  So read the docs.  Will do some work 
on this today myself and later tonight hopefully update the demo server 
with the latest code.

To be consistent I have removed '-' everywhere so session-id is now 
vscpsession. Also the parameter session is now vscpsession and is the 
same for both POST's and GETS.  user is vscpuser and password is 
vscpsecret. etc etc

Cheers
/Ake

ps I NEVER change API's normally. This is an exception and that rule 
will apply to this API also. ds

Den 2015-09-02 kl. 08:01, skrev Dinesh Guleria:
> >> Can you verify the bugfix please Dinesh?
> Is this change made to the vscpd demon ?
>
> Regards,
> Dinesh
>
> On Wed, Sep 2, 2015 at 12:52 AM, Åke Hedman <notifications@github.com>
> wrote:
>
> > Closed #167 <https://github.com/grodansparadis/vscp_software/issues/167>
> > via 53bfdaa
> > 
> <https://github.com/grodansparadis/vscp_software/commit/53bfdaa01a55b706ad670b7571ccabe625b5173c>
> > .
> >
> > —
> > Reply to this email directly or view it on GitHub
> > 
> <https://github.com/grodansparadis/vscp_software/issues/167#event-398183004>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/grodansparadis/vscp_software/issues/167#issuecomment-136946019>.
>

-- 
Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN
Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
http://www.grodansparadis.com http://www.vscp.org
