### ISSUE TITLE
Cross domain request error with JSONP 

### ISSUE THREAD

**Issue by dinguluer** [grodansparadis/vscp_software#168]
Javascript code using JSONP :---
$(document).ready(function() {

                      var url = "http://localhost:8080/vscp/rest?user=admin&password=d50c3180375c27927c22e42a379c3f67&format=json&op=1";

                      function jsonpCallback(response) {

                          alert('success');
                          //http://stackoverflow.com/questions/12806386/standard-json-api-response-format  -->  JSON API response format
                          //alert(response.id);
                          //alert(response.name);
                      }

                      $.ajax({
                          url: url,
                          dataType: 'jsonp',
                          error: function(xhr, status, error) {
                                     alert("error" + "  " + error.message);
                          },
                          success: jsonpCallback
                      });
                      return false;
});

vscpd webserver is sending the right response :--
{"success":true,"code":1,"message":"success","description":"Success","session-id":"e5a36e14b687c37b615dbc6a9506df5c","nEvents":0}

But ajax call giving error for this response i.e "Uncaught SyntaxError: Unexpected token :"

You need to change the data that is returned in the JSONP response to be a valid JavaScript statement, try assigning the JSON object to a variable, like var obj = {"success":true," .... } ;
OR
a callback to be added to the url :--
http://stackoverflow.com/questions/2067472/what-is-jsonp-all-about

**Comment by grodansparadis** [comment]
This should be fixed now. Check docs and sample.
