### ISSUE TITLE
Build issue on Linux

### ISSUE THREAD

**Issue by mamac** [grodansparadis/vscp_software#169]
Hi Ake,

I reinstalled my computer and got a fresh copy of the master branch.

Build doesn't work, see report: http://pastebin.com/0GfjeKuq

Using wxGTK 2.8.12

Thank you,
JM

**Comment by grodansparadis** [comment]
Hi

looks like it build OK. I know about the warnings. They are a dirty hack until a better solution is available.  Or am I wrong? Didn’t vscpworks build

**Comment by mamac** [comment]
Oops, I will check if WORKS works :-)

**Comment by mamac** [comment]
Indeed, it was a non issue, sorry!

**Comment by grodansparadis** [comment]
Me like non-issues. ;-)
