### ISSUE TITLE
Failed to write a string variable via websocket, which contains a semicolon inside.

### ISSUE THREAD

**Issue by BlueAndi** [grodansparadis/vscp_software#177]

**Comment by grodansparadis** [comment]
Hard to solve in a nice way.  Would it be OK to disallow it and make it 
possible by inserting it with an escape as "\;"

Den 2015-09-05 kl. 13:34, skrev Andreas Merkle:
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/grodansparadis/vscp_software/issues/177>.
>

-- 
Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN
Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
http://www.grodansparadis.com http://www.vscp.org

**Comment by BlueAndi** [comment]
Good question. I think we could live with it for now. I will update the javascript lib, so that it is automaticallty done.

**Comment by grodansparadis** [comment]
This reflects the tcp/ip variable setting as well I guess.  Have to 
think a bit about this. Good find.

Den 2015-09-05 kl. 17:09, skrev Andreas Merkle:
>
> Good question. I think we could live with it for now. I will update 
> the javascript lib, so that it is automaticallty done.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/grodansparadis/vscp_software/issues/177#issuecomment-137963654>.
>

-- 
Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN
Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
http://www.grodansparadis.com http://www.vscp.org

**Comment by grodansparadis** [comment]
Added info to the docs.

**Comment by BlueAndi** [comment]
That a semicolon is not allowed for variable names is fine.
But it is now not allowed as value too? Also it is escaped like '\;'?

**Comment by grodansparadis** [comment]
No we have to handle that outside of the interface. It could work with
some other escape as a semicolon screw things up. One way would be to
url encode values.But for now this will be the solution.

Den 2015-09-16 kl. 22:41, skrev Andreas Merkle:
> That a semicolon is not allowed for variable names is fine.
> But it is now not allowed as value too? Also it is escaped like '\;'?
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/grodansparadis/vscp_software/issues/177#issuecomment-140887738>.
> 

-- 
Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN
Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
http://www.grodansparadis.com http://www.vscp.org
