### ISSUE TITLE
Creating a empty string variable at the daemon is not possible.

### ISSUE THREAD

**Issue by BlueAndi** [grodansparadis/vscp_software#179]
I am sure it was possible this morning to create a empty string variable on the demoserver via websocket, but now it isn't anymore.

**Comment by grodansparadis** [comment]
I have updated it to the latest greatest a few minutes ago... ;-/

Den 2015-09-05 kl. 17:14, skrev Andreas Merkle:
>
> I am sure it was possible this morning to create a empty string 
> variable on the demoserver, but now it isn't anymore.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/grodansparadis/vscp_software/issues/179>.
>

-- 
Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN
Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
http://www.grodansparadis.com http://www.vscp.org

**Comment by BlueAndi** [comment]
ahh ... latest greatest ... *LOL*

**Comment by BlueAndi** [comment]
Could you update the demoserver with the last changes?

**Comment by grodansparadis** [comment]
Will do that tomorrow.  To late?

Den 2015-09-09 kl. 23:21, skrev Andreas Merkle:
> Could you update the demoserver with the last changes?
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/grodansparadis/vscp_software/issues/179#issuecomment-139049469>.
> 

-- 
Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN
Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
http://www.grodansparadis.com http://www.vscp.org

**Comment by BlueAndi** [comment]
Yes, thats ok ... will go to bed now. Good night!

**Comment by grodansparadis** [comment]
Goodnight

Den 2015-09-09 kl. 23:24, skrev Andreas Merkle:
> Yes, thats ok ... will go to bed now. Good night!
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/grodansparadis/vscp_software/issues/179#issuecomment-139050196>.
> 

-- 
Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN
Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
http://www.grodansparadis.com http://www.vscp.org

**Comment by BlueAndi** [comment]
Successful tested.

**Comment by grodansparadis** [comment]
Great!

Den 2015-09-10 kl. 19:19, skrev Andreas Merkle:
> Successful tested.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/grodansparadis/vscp_software/issues/179#issuecomment-139315998>.
> 

-- 
Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN
Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
http://www.grodansparadis.com http://www.vscp.org
