### ISSUE TITLE
VSCP client window: change connect/disconnect button behaviour

### ISSUE THREAD

**Issue by waaslandwolf** [grodansparadis/vscp_software#40]
Ake,

Here's a small feature request again :-)

I find that the behaviour of the red Connected/Diconnected button is sometimes confusing. Would it make sense to change the colour of the button to green if connected and to red if disconnected?

Perhaps a small and seemingly insignificant change, but I've found myself disconnecting the client because I assumed red meant it was disconnected.

Thanks,
David.

**Comment by waaslandwolf** [comment]
The Device Configuration window also has this button. Perhaps other windows too. Maybe it's best that they all have the same behaviour..

**Comment by grodansparadis** [comment]
Will go back to default colors for these.

**Comment by waaslandwolf** [comment]
Not sure what you mean?

On 12/01/2015 20:38, Ake Hedman wrote:
>
> Will go back to default colors for these.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/grodansparadis/vscp_software/issues/40#issuecomment-69631250>.
>



---
This email has been checked for viruses by Avast antivirus software.
http://www.avast.com

**Comment by grodansparadis** [comment]
The button will look as a standard togglebutton on the OS it is run. No 
special font, no special colour.

waaslandwolf skrev den 2015-01-12 21:02:
> Not sure what you mean?
>
> On 12/01/2015 20:38, Ake Hedman wrote:
> >
> > Will go back to default colors for these.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > 
> <https://github.com/grodansparadis/vscp_software/issues/40#issuecomment-69631250>.
> >
>
>
>
> ---
> This email has been checked for viruses by Avast antivirus software.
> http://www.avast.com
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/grodansparadis/vscp_software/issues/40#issuecomment-69635422>.
>

-- 
Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN
Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
http://www.grodansparadis.com http://www.vscp.org



---
Detta e-postmeddelande har sökts igenom efter virus med antivirusprogram från Avast.
http://www.avast.com
