### ISSUE TITLE
Issue writing paginated registers

### ISSUE THREAD

**Issue by waaslandwolf** [grodansparadis/vscp_software#42]
Ake,

I noticed some strange behaviour in vscpworks 1.0.0.44 (git pull 8 dec '14). I was trying to write a register on page 1, but it got written to page 0 instead (page not correctly selected).

Suppose the following:
- My MDF defines the DM to start on page 1, offset 0 (reg 1:0). There are 2 DM rows so the last DM register should be page 1 offset 15 (reg 1:15).
- My node's firmware defines REG_DECISION_MATRIX as location 256, which should be reg 1:0.
- If I read the device in vscpworks, in register 1:0 I find the same value as in reg 0:0. The next registers have the same behaviour.
- If I update the value in register 1:0 to 0x51, the client window shows:
  - READ_REGISTER request for reg 0x92 (146). This is the first page select register.
  - RW_RESPONSE with data 0x00. So page 0 is selected.
  - READ_REGISTER request for reg 0x93 (147). This is the second page select register.
  - RW_RESPONSE with data 0x00. So page 0 is selected.
  - WRITE_REGISTER with the destination node's GUID, reg 0x00, data 0x51. So 0x51 is written to reg 0:0 here instead of reg 1:0.
  - RW_RESPONSE 0x00, 0x51 confirming that 0x51 was written to reg 0:0.
  - if I re-read the registers I can see that in fact 0x51 was written in reg 0:0.
  - If I dump the contents of my node's EEPROM to a serial terminal, I can see that indeed reg 0:0 was witten.

- I was expecting:
  - 2 WRITE_REGISTERs to set reg 0x92 and 0x93 to page 1.
  - 2 RW_REPONSEs confirming that the page registers were set to page 1.
  - a WRITE_REGISTER to reg 0x00 and data 0x51.
  - a RW_RESPONSE to confirm the write.
  - register 1:0 to read 0x51.

- If I manually send events:
  - WRITE_REGISTER 0xF9, 0x92, 0x00 (set page MSB to 0x00) (RW_RESPONSE 0x92, 0x00)
  - WRITE_REGISTER 0xF9, 0x93, 0x01 (set page MSB to 0x01 = page 1)  (RW_RESPONSE 0x93, 0x01)
  - WRITE_REGISTER 0xF9, 0x00, 0x61 (write 0x61 to reg 1:00)
  - On the last write I get a RW_RESPONSE of 0x00, 0x9E while 0x00, 0x61 was expected. Strange.
  - If I check the registers in the device config window, I can't find the 0x9E in any of the registers.

Is this an error in vscpworks, or is it on my part? I suppose the latter since otherwise an obvious error like this should have already been noticed, but if so, where could my error be?

Thanks,
David.

**Comment by waaslandwolf** [comment]
Ake,

My firmware is now upgraded to the latest vscp_firmware git pull, so I am ready to troubleshoot this pagination issue with you. Let me know when you're ready. Not trying to push you here ;-)

**Comment by grodansparadis** [comment]
I did a small change to the firmware files yesterday you should probably 
copy it into your project. No bug things but for upcoming tests it is 
good to have the latest greatest.

waaslandwolf skrev den 2015-01-10 08:29:
>
> Ake,
>
> My firmware is now upgraded to the latest vscp_firmware git pull, so I 
> am ready to troubleshoot this pagination issue with you. Let me know 
> when you're ready. Not trying to push you here ;-)
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/grodansparadis/vscp_software/issues/42#issuecomment-69447178>.
>

-- 
Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN
Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
http://www.grodansparadis.com http://www.vscp.org



---
Detta e-postmeddelande har sökts igenom efter virus med antivirusprogram från Avast.
http://www.avast.com

**Comment by waaslandwolf** [comment]
Ok will do. I'll do it together with upgrading to your upcoming 
vscpworks release so that firmware and software are sure to match.

On 12/01/2015 15:20, Ake Hedman wrote:
> I did a small change to the firmware files yesterday you should probably
> copy it into your project. No bug things but for upcoming tests it is
> good to have the latest greatest.
>
> waaslandwolf skrev den 2015-01-10 08:29:
> >
> > Ake,
> >
> > My firmware is now upgraded to the latest vscp_firmware git pull, so I
> > am ready to troubleshoot this pagination issue with you. Let me know
> > when you're ready. Not trying to push you here ;-)
> >
> > —
> > Reply to this email directly or view it on GitHub
> > 
> <https://github.com/grodansparadis/vscp_software/issues/42#issuecomment-69447178>.
> >
>
> -- 
> Be Hungry - Stay Foolish!
> Åke Hedman, Grodans Paradis AB / Paradise of the Frog
> Brattbergavägen 17, 82050 LOS, SWEDEN
> Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
> http://www.grodansparadis.com http://www.vscp.org
>
>
>
> ---
> Detta e-postmeddelande har sökts igenom efter virus med 
> antivirusprogram från Avast.
> http://www.avast.com
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/grodansparadis/vscp_software/issues/42#issuecomment-69575792>.
>



---
This email has been checked for viruses by Avast antivirus software.
http://www.avast.com

**Comment by waaslandwolf** [comment]
Ake,

Now that I have VSCPworks 1.0.0.70 running I attempted to test reading/writing paginated registers again.

Registers as defined in MDF:

	    <reg page="1" offset="0">
			<name lang="en">Output PWM rate (PWM_OUT)</name>
			<description lang="en">
				File:mesp13.xml iteration 01\nThis register holds a value which, when the output is switched on, PWMs the outputs 1 to 6 at the defined rate.\nThe value is in tens of percents (0 - 10 for 0 to 100 percent).\n0 = output always off, 10 = output continuously on when switched on.
			</description>
			<access>rw</access>
		</reg>		


		<reg page="0" offset="0">
			<name lang="en">Zone</name>
			<description lang="en">Zone this module belongs to (EEPROM_ZONE)</description>
			<access>rw</access>
		</reg>
		<reg page="0" offset="1">
			<name lang="en">Subzone</name>
			<description lang="en">Subzone this module belongs to (EEPROM_SUBZONE)
	                </description>
			<access>rw</access>
		</reg>

When reading with the device configuration window in works these register show up as:

        0001:1 Output PWM rate (PWM_OUT)
        0000:0 Zone

In the firmware these registers are defined as:

        #define PWM_OUT                                                 (256* 1 + 1)
        #define EEPROM_ZONE			                       (256* 0 + 0)   //Zone node belongs to

So I register on page 1 location 0, one register on page 0 location 0.

When writing a value 0xAA into register PWM_OUT (page 0:reg 0) and reading it back, I find get:

- Events as monitored by VSCPworks:
    - CLASS2_LEVEL1_PROTOCOL, EXTENDED_PAGE_WRITE_REGISTER (0x0200, 0x026), data 0x37, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x12 (=GUID, ok), 0x00, __0x00__, 0x00, 0xAA
    - CLASS1_PROTOCOL, EXTENDED_PAGE_RW_RESPONSE (0x0000, 0x0027), data 0x00, 0x00, 0x00, 0x00, 0xAA
- firmware writes register 000:0, EEPROM location 66 (which is correct as per what was requested, =offset + page 0:0).
- the value 0xAA written to register 001:0 is read back at location 000:0. Location 001:00 remains empty.

Based on the spec I expected the sent event to be:

   - byte 0-15 (GUID), 0x00, __0x01__, 0x00, 0xAA

Data byte 	Description
0-15 	GUID.
16 	MSB of page where the register is located.
17 	LSB of page where the register is located.
18 	Register to write.
19 	Content of register. byte 20-buffer-size Optional extra data bytes to write. 

Clearly VSCPworks isn't requesting a paginated register to be written, and instead ignores the pagination as defined in the MDF and just requests the correct register location but on page 0.

David.

**Comment by grodansparadis** [comment]
Hi,

I think this is fixed but it can't be shared until I have finished some 
other stuff. Hopefully tomorrow I will be able to check in my changes.

/Ake

waaslandwolf skrev den 2015-02-08 19:35:
>
> Ake,
>
> Now that I have VSCPworks 1.0.0.70 running I attempted to test 
> reading/writing paginated registers again.
>
> Registers as defined in MDF:
>
> |     <reg page="1" offset="0">
>          <name lang="en">Output PWM rate (PWM_OUT)</name>
>          <description lang="en">
>              File:mesp13.xml iteration 01\nThis register holds a value which, when the output is switched on, PWMs the outputs 1 to 6 at the defined rate.\nThe value is in tens of percents (0 - 10 for 0 to 100 percent).\n0 = output always off, 10 = output continuously on when switched on.
>          </description>
>          <access>rw</access>
>      </reg>
> |
> |     <reg page="0" offset="0">
>          <name lang="en">Zone</name>
>          <description lang="en">Zone this module belongs to (EEPROM_ZONE)</description>
>          <access>rw</access>
>      </reg>
>      <reg page="0" offset="1">
>          <name lang="en">Subzone</name>
>          <description lang="en">Subzone this module belongs to (EEPROM_SUBZONE)
>                  </description>
>          <access>rw</access>
>      </reg>
> |
>
> When reading with the device configuration window in works these 
> register show up as:
>
> |     0001:1 Output PWM rate (PWM_OUT)
>      0000:0 Zone
> |
>
> In the firmware these registers are defined as:
>
> |     #define PWM_OUT                                                 (256* 1 + 1)
>      #define EEPROM_ZONE                                (256* 0 + 0)   //Zone node belongs to
> |
>
> So I register on page 1 location 0, one register on page 0 location 0.
>
> When writing a value 0xAA into register PWM_OUT (page 0:reg 0) and 
> reading it back, I find get:
>
>   * Events as monitored by VSCPworks:
>       o CLASS2_LEVEL1_PROTOCOL, EXTENDED_PAGE_WRITE_REGISTER (0x0200,
>         0x026), data 0x37, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
>         0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x12 (=GUID, ok),
>         0x00, *0x00*, 0x00, 0xAA
>       o CLASS1_PROTOCOL, EXTENDED_PAGE_RW_RESPONSE (0x0000, 0x0027),
>         data 0x00, 0x00, 0x00, 0x00, 0xAA
>   * firmware writes register 000:0, EEPROM location 66 (which is
>     correct as per what was requested, =offset + page 0:0).
>   * the value 0xAA written to register 001:0 is read back at location
>     000:0. Location 001:00 remains empty.
>
> Based on the spec I expected the sent event to be:
>
>   * byte 0-15 (GUID), 0x00, *0x01*, 0x00, 0xAA
>
> Data byte Description
> 0-15 GUID.
> 16 MSB of page where the register is located.
> 17 LSB of page where the register is located.
> 18 Register to write.
> 19 Content of register. byte 20-buffer-size Optional extra data bytes 
> to write.
>
> Clearly VSCPworks isn't requesting a paginated register to be written, 
> and instead ignores the pagination as defined in the MDF and just 
> requests the correct register location but on page 0.
>
> David.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/grodansparadis/vscp_software/issues/42#issuecomment-73424306>.
>

-- 
Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN
Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
http://www.grodansparadis.com http://www.vscp.org



---
Detta e-postmeddelande har sökts igenom efter virus med antivirusprogram från Avast.
http://www.avast.com

**Comment by waaslandwolf** [comment]
Ake,

Ok no worries, it's just because you closed the issue that I re-tested 
it. Let me know when you commit so I can test. No real hurry, I have a 
working work-around.

David.

On 9/02/2015 9:48, Ake Hedman wrote:
> Hi,
>
> I think this is fixed but it can't be shared until I have finished some
> other stuff. Hopefully tomorrow I will be able to check in my changes.
>
> /Ake
>
> waaslandwolf skrev den 2015-02-08 19:35:
> >
> > Ake,
> >
> > Now that I have VSCPworks 1.0.0.70 running I attempted to test
> > reading/writing paginated registers again.
> >
> > Registers as defined in MDF:
> >
> > | <reg page="1" offset="0">
> > <name lang="en">Output PWM rate (PWM_OUT)</name>
> > <description lang="en">
> > File:mesp13.xml iteration 01\nThis register holds a value which, 
> when the output is switched on, PWMs the outputs 1 to 6 at the defined 
> rate.\nThe value is in tens of percents (0 - 10 for 0 to 100 
> percent).\n0 = output always off, 10 = output continuously on when 
> switched on.
> > </description>
> > <access>rw</access>
> > </reg>
> > |
> > | <reg page="0" offset="0">
> > <name lang="en">Zone</name>
> > <description lang="en">Zone this module belongs to 
> (EEPROM_ZONE)</description>
> > <access>rw</access>
> > </reg>
> > <reg page="0" offset="1">
> > <name lang="en">Subzone</name>
> > <description lang="en">Subzone this module belongs to (EEPROM_SUBZONE)
> > </description>
> > <access>rw</access>
> > </reg>
> > |
> >
> > When reading with the device configuration window in works these
> > register show up as:
> >
> > | 0001:1 Output PWM rate (PWM_OUT)
> > 0000:0 Zone
> > |
> >
> > In the firmware these registers are defined as:
> >
> > | #define PWM_OUT (256* 1 + 1)
> > #define EEPROM_ZONE (256* 0 + 0) //Zone node belongs to
> > |
> >
> > So I register on page 1 location 0, one register on page 0 location 0.
> >
> > When writing a value 0xAA into register PWM_OUT (page 0:reg 0) and
> > reading it back, I find get:
> >
> > * Events as monitored by VSCPworks:
> > o CLASS2_LEVEL1_PROTOCOL, EXTENDED_PAGE_WRITE_REGISTER (0x0200,
> > 0x026), data 0x37, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
> > 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x12 (=GUID, ok),
> > 0x00, *0x00*, 0x00, 0xAA
> > o CLASS1_PROTOCOL, EXTENDED_PAGE_RW_RESPONSE (0x0000, 0x0027),
> > data 0x00, 0x00, 0x00, 0x00, 0xAA
> > * firmware writes register 000:0, EEPROM location 66 (which is
> > correct as per what was requested, =offset + page 0:0).
> > * the value 0xAA written to register 001:0 is read back at location
> > 000:0. Location 001:00 remains empty.
> >
> > Based on the spec I expected the sent event to be:
> >
> > * byte 0-15 (GUID), 0x00, *0x01*, 0x00, 0xAA
> >
> > Data byte Description
> > 0-15 GUID.
> > 16 MSB of page where the register is located.
> > 17 LSB of page where the register is located.
> > 18 Register to write.
> > 19 Content of register. byte 20-buffer-size Optional extra data bytes
> > to write.
> >
> > Clearly VSCPworks isn't requesting a paginated register to be written,
> > and instead ignores the pagination as defined in the MDF and just
> > requests the correct register location but on page 0.
> >
> > David.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > 
> <https://github.com/grodansparadis/vscp_software/issues/42#issuecomment-73424306>.
> >
>
> -- 
> Be Hungry - Stay Foolish!
> Åke Hedman, Grodans Paradis AB / Paradise of the Frog
> Brattbergavägen 17, 82050 LOS, SWEDEN
> Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
> http://www.grodansparadis.com http://www.vscp.org
>
>
>
> ---
> Detta e-postmeddelande har sökts igenom efter virus med 
> antivirusprogram från Avast.
> http://www.avast.com
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/grodansparadis/vscp_software/issues/42#issuecomment-73474692>.
>



---
This email has been checked for viruses by Avast antivirus software.
http://www.avast.com
