### ISSUE TITLE
Feature request: filter heartbeat messages

### ISSUE THREAD

**Issue by waaslandwolf** [grodansparadis/vscp_software#46]
Ake,

I find that when monitoring VSCP traffic with the VSCP works monitor window, after a while the receive event window gets flooded with heartbeat messages. It would be nice if there was an option to filter out these events so that they don't appear in the received event window any more. Perhaps this is something of value which is easy to implement?

David.

**Comment by grodansparadis** [comment]
Hi David,

cant you just set a filter that filter them out? With a bit of thougth 
you should be able to receive all other events or at least the once you 
are interested in.

But generally I agree it would have been nice with a mechanism where you 
could tell which events you want to see and which you don't want.  Has 
been on my list of todo's for a while and some day it might be a reality 
even.

/Ake

waaslandwolf skrev den 2015-01-13 10:58:
>
> Ake,
>
> I find that when monitoring VSCP traffic with the VSCP works monitor 
> window, after a while the receive event window gets flooded with 
> heartbeat messages. It would be nice if there was an option to filter 
> out these events so that they don't appear in the received event 
> window any more. Perhaps this is something of value which is easy to 
> implement?
>
> David.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/grodansparadis/vscp_software/issues/46>.
>

-- 
Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN
Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
http://www.grodansparadis.com http://www.vscp.org



---
Detta e-postmeddelande har sökts igenom efter virus med antivirusprogram från Avast.
http://www.avast.com

**Comment by waaslandwolf** [comment]
Ake,

Yes setting a filter make the most sense, but when I tested this by 
selecting Configuration - Set Filter, I got a message "Sorry this 
functionality isn't available yet..."

David.

On 13/01/2015 11:05, Ake Hedman wrote:
> Hi David,
>
> cant you just set a filter that filter them out? With a bit of thougth
> you should be able to receive all other events or at least the once you
> are interested in.
>
> But generally I agree it would have been nice with a mechanism where you
> could tell which events you want to see and which you don't want. Has
> been on my list of todo's for a while and some day it might be a reality
> even.
>
> /Ake
>
> waaslandwolf skrev den 2015-01-13 10:58:
> >
> > Ake,
> >
> > I find that when monitoring VSCP traffic with the VSCP works monitor
> > window, after a while the receive event window gets flooded with
> > heartbeat messages. It would be nice if there was an option to filter
> > out these events so that they don't appear in the received event
> > window any more. Perhaps this is something of value which is easy to
> > implement?
> >
> > David.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/grodansparadis/vscp_software/issues/46>.
> >
>
> -- 
> Be Hungry - Stay Foolish!
> Åke Hedman, Grodans Paradis AB / Paradise of the Frog
> Brattbergavägen 17, 82050 LOS, SWEDEN
> Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
> http://www.grodansparadis.com http://www.vscp.org
>
>
>
> ---
> Detta e-postmeddelande har sökts igenom efter virus med 
> antivirusprogram från Avast.
> http://www.avast.com
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/grodansparadis/vscp_software/issues/46#issuecomment-69721472>.
>



---
This email has been checked for viruses by Avast antivirus software.
http://www.avast.com

**Comment by grodansparadis** [comment]
No what you get there is exactly what we talk about here. But you can 
set a filter on the interface also.

/Ake

waaslandwolf skrev den 2015-01-13 11:29:
> Ake,
>
> Yes setting a filter make the most sense, but when I tested this by
> selecting Configuration - Set Filter, I got a message "Sorry this
> functionality isn't available yet..."
>
> David.
>
> On 13/01/2015 11:05, Ake Hedman wrote:
> > Hi David,
> >
> > cant you just set a filter that filter them out? With a bit of thougth
> > you should be able to receive all other events or at least the once you
> > are interested in.
> >
> > But generally I agree it would have been nice with a mechanism where you
> > could tell which events you want to see and which you don't want. Has
> > been on my list of todo's for a while and some day it might be a reality
> > even.
> >
> > /Ake
> >
> > waaslandwolf skrev den 2015-01-13 10:58:
> > >
> > > Ake,
> > >
> > > I find that when monitoring VSCP traffic with the VSCP works monitor
> > > window, after a while the receive event window gets flooded with
> > > heartbeat messages. It would be nice if there was an option to filter
> > > out these events so that they don't appear in the received event
> > > window any more. Perhaps this is something of value which is easy to
> > > implement?
> > >
> > > David.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/grodansparadis/vscp_software/issues/46>.
> > >
> >
> > --
> > Be Hungry - Stay Foolish!
> > Åke Hedman, Grodans Paradis AB / Paradise of the Frog
> > Brattbergavägen 17, 82050 LOS, SWEDEN
> > Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
> > http://www.grodansparadis.com http://www.vscp.org
> >
> >
> >
> > ---
> > Detta e-postmeddelande har sökts igenom efter virus med
> > antivirusprogram från Avast.
> > http://www.avast.com
> >
> > —
> > Reply to this email directly or view it on GitHub
> > 
> <https://github.com/grodansparadis/vscp_software/issues/46#issuecomment-69721472>.
> >
>
>
>
> ---
> This email has been checked for viruses by Avast antivirus software.
> http://www.avast.com
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/grodansparadis/vscp_software/issues/46#issuecomment-69724504>.
>

-- 
Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN
Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
http://www.grodansparadis.com http://www.vscp.org



---
Detta e-postmeddelande har sökts igenom efter virus med antivirusprogram från Avast.
http://www.avast.com

**Comment by waaslandwolf** [comment]
Ah I see... I'll give that a go.


On 13/01/2015 11:36, Ake Hedman wrote:
> No what you get there is exactly what we talk about here. But you can
> set a filter on the interface also.
>
> /Ake
>
> waaslandwolf skrev den 2015-01-13 11:29:
> > Ake,
> >
> > Yes setting a filter make the most sense, but when I tested this by
> > selecting Configuration - Set Filter, I got a message "Sorry this
> > functionality isn't available yet..."
> >
> > David.
> >
> > On 13/01/2015 11:05, Ake Hedman wrote:
> > > Hi David,
> > >
> > > cant you just set a filter that filter them out? With a bit of thougth
> > > you should be able to receive all other events or at least the 
> once you
> > > are interested in.
> > >
> > > But generally I agree it would have been nice with a mechanism 
> where you
> > > could tell which events you want to see and which you don't want. Has
> > > been on my list of todo's for a while and some day it might be a 
> reality
> > > even.
> > >
> > > /Ake
> > >
> > > waaslandwolf skrev den 2015-01-13 10:58:
> > > >
> > > > Ake,
> > > >
> > > > I find that when monitoring VSCP traffic with the VSCP works monitor
> > > > window, after a while the receive event window gets flooded with
> > > > heartbeat messages. It would be nice if there was an option to 
> filter
> > > > out these events so that they don't appear in the received event
> > > > window any more. Perhaps this is something of value which is easy to
> > > > implement?
> > > >
> > > > David.
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <https://github.com/grodansparadis/vscp_software/issues/46>.
> > > >
> > >
> > > --
> > > Be Hungry - Stay Foolish!
> > > Åke Hedman, Grodans Paradis AB / Paradise of the Frog
> > > Brattbergavägen 17, 82050 LOS, SWEDEN
> > > Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
> > > http://www.grodansparadis.com http://www.vscp.org
> > >
> > >
> > >
> > > ---
> > > Detta e-postmeddelande har sökts igenom efter virus med
> > > antivirusprogram från Avast.
> > > http://www.avast.com
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > >
> > 
> <https://github.com/grodansparadis/vscp_software/issues/46#issuecomment-69721472>.
> > >
> >
> >
> >
> > ---
> > This email has been checked for viruses by Avast antivirus software.
> > http://www.avast.com
> >
> > —
> > Reply to this email directly or view it on GitHub
> > 
> <https://github.com/grodansparadis/vscp_software/issues/46#issuecomment-69724504>.
> >
>
> -- 
> Be Hungry - Stay Foolish!
> Åke Hedman, Grodans Paradis AB / Paradise of the Frog
> Brattbergavägen 17, 82050 LOS, SWEDEN
> Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
> http://www.grodansparadis.com http://www.vscp.org
>
>
>
> ---
> Detta e-postmeddelande har sökts igenom efter virus med 
> antivirusprogram från Avast.
> http://www.avast.com
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/grodansparadis/vscp_software/issues/46#issuecomment-69725307>.
>



---
This email has been checked for viruses by Avast antivirus software.
http://www.avast.com

**Comment by waaslandwolf** [comment]
Ake,

Just wanted to let you know that I am enjoying the new filter 
functionality every day. Such a great feature to be able to save and 
load filters on the fly! I have >20 nodes on the bus now so filtering 
events sure helps troubleshooting!

David.

On 2/02/2015 14:01, Ake Hedman wrote:
>
> Closed #46 <https://github.com/grodansparadis/vscp_software/issues/46>.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/grodansparadis/vscp_software/issues/46#event-228481349>.
>



---
This email has been checked for viruses by Avast antivirus software.
http://www.avast.com

**Comment by grodansparadis** [comment]
David,

Good to here. I actually find it useful myself to. ;-)

/Ake

waaslandwolf skrev den 2015-02-18 20:35:
> Ake,
>
> Just wanted to let you know that I am enjoying the new filter
> functionality every day. Such a great feature to be able to save and
> load filters on the fly! I have >20 nodes on the bus now so filtering
> events sure helps troubleshooting!
>
> David.
>
> On 2/02/2015 14:01, Ake Hedman wrote:
> >
> > Closed #46 <https://github.com/grodansparadis/vscp_software/issues/46>.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > 
> <https://github.com/grodansparadis/vscp_software/issues/46#event-228481349>.
> >
>
>
>
> ---
> This email has been checked for viruses by Avast antivirus software.
> http://www.avast.com
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/grodansparadis/vscp_software/issues/46#issuecomment-74931818>.
>

-- 
Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN
Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
http://www.grodansparadis.com http://www.vscp.org



---
Detta e-postmeddelande har sökts igenom efter virus med antivirusprogram från Avast.
http://www.avast.com
