### ISSUE TITLE
Compile error devicebootloaderwizard.cpp under windows

### ISSUE THREAD

**Issue by BlueAndi** [grodansparadis/vscp_software#52]
Hi Ake,

today I pulled again and now I get a compile error in
devicebootloaderwizard.cpp regarding fetchIterfaceGUID(), which can not be found.
Can you check please?

Best regards
Andreas

**Comment by grodansparadis** [comment]
Fixed now. My mistake sorry.

Andreas Merkle skrev den 2015-01-30 19:38:
>
> Hi Ake,
>
> today I pulled again and now I get a compile error in
> devicebootloaderwizard.cpp regarding fetchIterfaceGUID(), which can 
> not be found.
> Can you check please?
>
> Best regards
> Andreas
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/grodansparadis/vscp_software/issues/52>.
>

-- 
Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN
Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
http://www.grodansparadis.com http://www.vscp.org



---
Detta e-postmeddelande har sökts igenom efter virus med antivirusprogram från Avast.
http://www.avast.com
