### ISSUE TITLE
vscphelper.cpp: Expression is always false because 'else if' condition matches previous condition at line 840.

### ISSUE THREAD

**Issue by BlueAndi** [grodansparadis/vscp_software#71]
Hi Ake,

vscphelper.cpp contains an expression at line 846 which is always false because 'else if' condition matches previous condition at line 840.

One condition should compare against something other than VSCP_CLASS1_MEASUREMENT, the question is, against what? :-)

Best regards
Andreas

**Comment by grodansparadis** [comment]
I'm very unresponsive tonight Andy. Searching for the segfault people is 
reporting in. A hard one. But I will check as soon as I can.

Andreas Merkle skrev den 2015-02-03 20:28:
>
> Hi Ake,
>
> vscphelper.cpp contains an expression at line 846 which is always 
> false because 'else if' condition matches previous condition at line 840.
>
> One condition should compare against something other than 
> VSCP_CLASS1_MEASUREMENT, the question is, against what? :-)
>
> Best regards
> Andreas
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/grodansparadis/vscp_software/issues/71>.
>

-- 
Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN
Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
http://www.grodansparadis.com http://www.vscp.org



---
Detta e-postmeddelande har sökts igenom efter virus med antivirusprogram från Avast.
http://www.avast.com

**Comment by BlueAndi** [comment]
Good hunting! :-)

**Comment by grodansparadis** [comment]
Fixed! Thanks!
