### ISSUE TITLE
Cannot open include file "afxres.h"

### ISSUE THREAD

**Issue by BlueAndi** [grodansparadis/vscp_software#81]
Hi Ake,

I get the error message above if I try to compile the vscphelper. Do you really need it?

Best regards
Andreas

**Comment by grodansparadis** [comment]
Not the lib but the helpertest does. But both compiles fine here.

Andreas Merkle skrev den 2015-02-12 21:11:
>
> Hi Ake,
>
> I get the error message above if I try to compile the vscphelper. Do 
> you really need it?
>
> Best regards
> Andreas
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/grodansparadis/vscp_software/issues/81>.
>

-- 
Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN
Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
http://www.grodansparadis.com http://www.vscp.org



---
Detta e-postmeddelande har sökts igenom efter virus med antivirusprogram från Avast.
http://www.avast.com

**Comment by BlueAndi** [comment]
Because you have MFC installed and I have the express edition without. :-)

**Comment by grodansparadis** [comment]
no mfc there so it can go if precompiled header is turned of.  Gone now.

Andreas Merkle skrev den 2015-02-12 21:29:
>
> Because you have MFC installed and I have the express edition without. :-)
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/grodansparadis/vscp_software/issues/81#issuecomment-74146492>.
>

-- 
Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN
Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
http://www.grodansparadis.com http://www.vscp.org



---
Detta e-postmeddelande har sökts igenom efter virus med antivirusprogram från Avast.
http://www.avast.com

**Comment by BlueAndi** [comment]
Thanks for the fast support ... as always. :-)

**Comment by BlueAndi** [comment]
afx stuff still there:
src/vscp/helperlib/windows/vscphelper.rc
```
#include "afxres.h"
```
and
```
#include "afxres.rc"
```
