### ISSUE TITLE
Question about vscphelperlib dll version function

### ISSUE THREAD

**Issue by BlueAndi** [grodansparadis/vscp_software#83]
Why does the vscphlp_getDLLVersion() needs an established connection? It shall only return the version constants of the dll, isn't it?

How about the vscphlp_getVersion() function?

**Comment by grodansparadis** [comment]
No need at all but it looks good... ;-)))))

Andreas Merkle skrev den 2015-02-12 21:43:
>
> Why does the vscphlp_getDLLVersion() needs an established connection? 
> It shall only return the version constants of the dll, isn't it?
>
> How about the vscphlp_getVersion() function?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/grodansparadis/vscp_software/issues/83>.
>

-- 
Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN
Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
http://www.grodansparadis.com http://www.vscp.org



---
Detta e-postmeddelande har sökts igenom efter virus med antivirusprogram från Avast.
http://www.avast.com

**Comment by BlueAndi** [comment]
*LOL* ... copy&paste king ;-)

**Comment by grodansparadis** [comment]
;-)  Consider it gone, soon...

Andreas Merkle skrev den 2015-02-12 22:14:
>
> /LOL/ ... copy&paste king ;-)
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/grodansparadis/vscp_software/issues/83#issuecomment-74154036>.
>

-- 
Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN
Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
http://www.grodansparadis.com http://www.vscp.org



---
Detta e-postmeddelande har sökts igenom efter virus med antivirusprogram från Avast.
http://www.avast.com

**Comment by BlueAndi** [comment]
okeydokey

**Comment by BlueAndi** [comment]
BTW does vscpworks should display a temperature if it receives one?

**Comment by grodansparadis** [comment]
Yes at least for the the normalized and the floating point values. 
Hopefully also the string variant.  The websocket event sample can send 
some temperatures.

I am looking into the page problem now at last  so hopefully it is 
resolved until tomorrow.  That is a programmers tomorrow == soon btw.

/Ake

Andreas Merkle skrev den 2015-02-12 22:17:
>
> BTW does vscpworks should display a temperature if it receives one?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/grodansparadis/vscp_software/issues/83#issuecomment-74154523>.
>

-- 
Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN
Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
http://www.grodansparadis.com http://www.vscp.org



---
Detta e-postmeddelande har sökts igenom efter virus med antivirusprogram från Avast.
http://www.avast.com

**Comment by BlueAndi** [comment]
At the moment my node sends CLASS_MEASUREZONE temperature events with normalized values, maybe thats the problem ... hmm ...

Isn't it more dark than bright at your side at the moment? So you have 23 hours before tomorrow :-)

**Comment by grodansparadis** [comment]
Andreas Merkle skrev den 2015-02-12 22:26:
>
> At the moment my node sends CLASS_MEASUREZONE temperature events with 
> normalized values, maybe thats the problem ... hmm ...
>
It can be CLASS_MEASUREZONE that is the problem. Pretty new. Try 
CLASS_MEASUREMENT

> Isn't it more dark than bright at your side at the moment? So you have 
> 23 hours before tomorrow :-)
>
;-)


-- 
Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN
Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
http://www.grodansparadis.com http://www.vscp.org


---
Detta e-postmeddelande har sökts igenom efter virus med antivirusprogram från Avast.
http://www.avast.com

**Comment by grodansparadis** [comment]
I checked this. The handle is actually needed as the ´driver object can be different for different clients. So this will stay.
