### ISSUE TITLE
Normalized values are shown incorrect in vscpworks

### ISSUE THREAD

**Issue by BlueAndi** [grodansparadis/vscp_software#85]
Example:
Payload: 88 81 01 07
Shown 2630.000000 C
Expected 26.30000000 C

**Comment by grodansparadis** [comment]
The correct format is 88 01 01 07 to get 26.3 C   I get confused when I 
see this and have to go to the spec and see that it's explained the 
wrong way around there for some reason. Normally I would say that the 
spec is always right but all code I know of is the other way around.  Or 
maybe I'm just tired now and mess it all up. Will check tomorrow and 
come back. This was bad.

Andreas Merkle skrev den 2015-02-12 23:07:
>
> Example:
> Payload: 88 81 01 07
> Shown 2630.000000 C
> Expected 26.30000000 C
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/grodansparadis/vscp_software/issues/85>.
>

-- 
Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN
Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
http://www.grodansparadis.com http://www.vscp.org



---
Detta e-postmeddelande har sökts igenom efter virus med antivirusprogram från Avast.
http://www.avast.com

**Comment by BlueAndi** [comment]
Oups ... hear you tomorrow ... I am tired too and my bed asks for me.

**Comment by grodansparadis** [comment]
Same here. Sweet dreams.


Andreas Merkle skrev den 2015-02-12 23:53:
>
> Oups ... hear you tomorrow ... I am tired too and my bed asks for me.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/grodansparadis/vscp_software/issues/85#issuecomment-74171166>.
>

-- 
Be Hungry - Stay Foolish!
Åke Hedman, Grodans Paradis AB / Paradise of the Frog
Brattbergavägen 17, 82050 LOS, SWEDEN
Phone: +46 (0)840011835 CellPhone: +46 (0)730-533146
http://www.grodansparadis.com http://www.vscp.org



---
Detta e-postmeddelande har sökts igenom efter virus med antivirusprogram från Avast.
http://www.avast.com
