### ISSUE TITLE
VSCPworks 1.0.0.70 attempts to write reserved registers

### ISSUE THREAD

**Issue by waaslandwolf** [grodansparadis/vscp_software#89]
Scenario:

- read a node's registers (all registers)
- save registers to file
- change node Id in device config window
- load registers from file
- click Update

VSCP will write all registers, even the VSCP reserved registers 0x80-0xFF. The node handles this correctly by refusing to write the reserved registers, and instead returning the value.

**Comment by grodansparadis** [comment]
This is a good find which also had page related errors. The functionality has changed slightly as a valid register set now must be have been read in before new registers can be loaded. If not an update will be done before registers are loaded.
